name: mvvm_riverpod
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

# flutter pub add freezed_annotation
# flutter pub add dev:build_runner
# flutter pub add dev:freezed
# # if using freezed to generate fromJson/toJson, also add:
# flutter pub add json_annotation
# flutter pub add dev:json_serializable

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  uuid: ^4.5.1
  
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.14
  riverpod_generator: ^2.6.1
  
  freezed: ^2.5.7
  json_serializable: ^6.9.0



flutter:
  uses-material-design: true
